# Site settings
title: Leseliste
email: jens@schauderhaft.de
description: > # this means to ignore newlines until "baseurl:"
  Dies ist eine Liste von B端chern, die Lara, Finn und Jens Schauder
  gelesen haben, lesen oder noch lesen wollen.
  Links hinter den B端cher f端hren auf Amazon.de und wir bekommen eventuell irgendwann
  einen Gutschein daf端r :)
# baseurl: {{site.github.url}} # the subpath of your site, e.g. /blog/
twitter_username: jensschauder
github_username:  schauder

# Build settings
# no code highlighting for now, since it does not work on windows. see for example http://stackoverflow.com/questions/17364028/jekyll-on-windows-pygments-not-working/17404260#17404260 
highlighter: false

# Build settings
markdown: kramdown
